/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.tugasakhir;
import javax.swing.JOptionPane;

/**
 *
 * @author dewan
 */
public class TokoLaptop extends javax.swing.JFrame {
   public String[][] harga = {{"Asis Tuf FX505DU","10000000","8"},
                              {"Asis Tuf FX505DV","12000000","7"},
                              {"Asis ROG GL503GM","15000000","9"},
                              {"Asis ROG Zephyrus","19000000","10"},
                              {"Asis Vivobook","7000000","5"},
                              {"Ocer Nitro 5","11000000","7"},
                              {"Ocer Predator Gaming","17000000","8"},
                              {"Hape Pavilion 15","10800000","8"},
                              {"Hape Omen","15500000","7"},
                              {"Hape Victus Pro","13500000","7"},
                              {"Lenova Ideapad 3","7500000","5"},
                              {"Lenova Ideapad 5","8500000","4"}};
           
                              
           
                              
   
  
           /**
     * Creates new form ta
     */
    public TokoLaptop() {
        initComponents();
        
    }
    public int Total_ongkir;
    public int Total_harga;
    public int kembalian;
    public int jawab;
    public void cancel(){
     TxtNamaPelanggan.setText("");
     TxtHargaBarang.setText("");
     TxtAlamat.setText("");
     TxtBerat.setText("");
     TxtOngkir.setText("");
     TxtTotalOngkir.setText("");
     TxtTotalHarga.setText("");
     TxtNominalBayar.setText("");
     TxtKembalian.setText("");
     CBPilihanLaptop.setSelectedItem("Pilihan Laptop");
     CBEkspedisi.setSelectedItem("Pilih");
    
    };
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        TxtNamaPelanggan = new javax.swing.JTextField();
        CBPilihanLaptop = new javax.swing.JComboBox<>();
        TxtHargaBarang = new javax.swing.JTextField();
        TxtAlamat = new javax.swing.JTextField();
        TxtBerat = new javax.swing.JTextField();
        TxtOngkir = new javax.swing.JTextField();
        CBEkspedisi = new javax.swing.JComboBox<>();
        TxtTotalOngkir = new javax.swing.JTextField();
        TxtTotalHarga = new javax.swing.JTextField();
        TxtNominalBayar = new javax.swing.JTextField();
        TxtKembalian = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        JBCheckout = new javax.swing.JButton();
        JBCancel = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(222, 222, 222));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Toko Laptop Online");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama Pelanggan :");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Pilihan Laptop :");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Harga Barang :");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Berat :");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Alamat Pengiriman :");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ongkir/kg");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Ekspedisi : ");

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Total Ongkir");

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Total harga :");

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Nominal Pembayaran :");

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Kembalian :");

        CBPilihanLaptop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilihan Laptop", "Asis Tuf FX505DU", "Asis Tuf FX505DV", "Asis ROG GL503GM", "Asis ROG Zephyrus", "Asis Vivobook", "Ocer Nitro 5", "Ocer Predator Gaming", "Hape Pavilion 15", "Hape Omen", "Hape Victus Pro", "Lenova Ideapad 3", "Lenova Ideapad 5" }));
        CBPilihanLaptop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBPilihanLaptopActionPerformed(evt);
            }
        });

        TxtHargaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtHargaBarangActionPerformed(evt);
            }
        });

        CBEkspedisi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "JNX", "TIKA", "SiBanter", "NinjaHatori" }));
        CBEkspedisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBEkspedisiActionPerformed(evt);
            }
        });

        TxtTotalOngkir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTotalOngkirActionPerformed(evt);
            }
        });

        TxtTotalHarga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtTotalHargaMouseClicked(evt);
            }
        });
        TxtTotalHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTotalHargaActionPerformed(evt);
            }
        });

        TxtNominalBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNominalBayarActionPerformed(evt);
            }
        });
        TxtNominalBayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtNominalBayarKeyReleased(evt);
            }
        });

        TxtKembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtKembalianActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(TxtKembalian))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtNominalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(27, 27, 27)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TxtNamaPelanggan)
                                .addComponent(CBPilihanLaptop, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TxtHargaBarang)
                                .addComponent(TxtAlamat)
                                .addComponent(TxtOngkir)
                                .addComponent(TxtTotalOngkir)
                                .addComponent(TxtTotalHarga)
                                .addComponent(CBEkspedisi, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TxtBerat, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CBPilihanLaptop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TxtHargaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TxtBerat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TxtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBEkspedisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtOngkir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(TxtTotalOngkir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(TxtTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(TxtNominalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(TxtKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 51, 51));

        jButton1.setText("Clear");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        JBCheckout.setText("Checkout");
        JBCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCheckoutActionPerformed(evt);
            }
        });

        JBCancel.setText("Cancel");
        JBCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(29, 29, 29)
                .addComponent(JBCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JBCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TxtHargaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtHargaBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtHargaBarangActionPerformed

    private void CBPilihanLaptopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBPilihanLaptopActionPerformed
        // TODO add your handling code here:
         if(CBPilihanLaptop.getSelectedItem().equals("Pilihan Laptop")){
            TxtHargaBarang.setText("");
            }
            for(int i=0;i<harga.length;i++){
                if(CBPilihanLaptop.getSelectedItem().equals(harga[i][0])){
            TxtHargaBarang.setText(harga[i][1]); TxtBerat.setText(harga[i][2]);  
            }
            }
         
        
    }//GEN-LAST:event_CBPilihanLaptopActionPerformed

    
    
    private void CBEkspedisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBEkspedisiActionPerformed
        // TODO add your handling code here:
        

        if(CBEkspedisi.getSelectedItem().equals("Pilih")){
           TxtOngkir.setText("");
        }else if(CBEkspedisi.getSelectedItem().equals("JNX")){
           TxtOngkir.setText("10000"); 
        }else if(CBEkspedisi.getSelectedItem().equals("TIKA")){
           TxtOngkir.setText("8000"); 
        }else if(CBEkspedisi.getSelectedItem().equals("SiBanter")){
           TxtOngkir.setText("7000"); 
        }else if(CBEkspedisi.getSelectedItem().equals("NinjaHatori")){
           TxtOngkir.setText("9000"); 
        }
            int Ongkir = Integer.parseInt(TxtOngkir.getText());
            int Berat = Integer.parseInt(TxtBerat.getText());
            Total_ongkir = Ongkir*Berat;TxtTotalOngkir.setText(String.valueOf(Total_ongkir));
            int TotOngkir = Integer.parseInt(TxtTotalOngkir.getText());
            int Hargax = Integer.parseInt(TxtHargaBarang.getText());
            Total_harga = TotOngkir+Hargax;TxtTotalHarga.setText(String.valueOf(Total_harga)); 
       
    }//GEN-LAST:event_CBEkspedisiActionPerformed

    private void TxtTotalOngkirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTotalOngkirActionPerformed
        // TODO add your handling code here:
        
       
            
       
               
    }//GEN-LAST:event_TxtTotalOngkirActionPerformed

    private void TxtTotalHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTotalHargaActionPerformed
        // TODO add your handling code here:
        
        
    
        
        
    }//GEN-LAST:event_TxtTotalHargaActionPerformed

    private void TxtTotalHargaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtTotalHargaMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TxtTotalHargaMouseClicked

    private void TxtKembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtKembalianActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_TxtKembalianActionPerformed

    private void TxtNominalBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNominalBayarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TxtNominalBayarActionPerformed

    private void JBCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCheckoutActionPerformed
        // TODO add your handling code here:
        
        if(TxtNamaPelanggan.getText().isEmpty()||TxtAlamat.getText().isEmpty()||TxtNominalBayar.getText().isEmpty())
        {JOptionPane.showMessageDialog(rootPane,"Data Belum Lengkap!", "Toko Laptop Online", JOptionPane.INFORMATION_MESSAGE);
        }else{
       JOptionPane.showMessageDialog(null, "Terima Kasih sudah belanja di toko kami :) \n"+ 
                    "Nama Pelanggan: "+TxtNamaPelanggan.getText()+"\n"
                     +"Unit laptop: "+CBPilihanLaptop.getSelectedItem()+ "\n"
                     + "Alamat: "+TxtAlamat.getText()+ "\n"
                     +"!!!Tranksaksi Berhasil!!!", "Toko Laptop Online", JOptionPane.INFORMATION_MESSAGE);
            int jawab = JOptionPane.showConfirmDialog(null, "apakah anda ingin belanja lagi?");
        
            
            switch(jawab){
    case JOptionPane.YES_OPTION: 
        setVisible(false);
        new TokoLaptop().setVisible(true);
        break;
    case JOptionPane.NO_OPTION:
        System.exit(0);
        break;
    case JOptionPane.CANCEL_OPTION:
        setVisible(false);
        new Login().setVisible(true);
        

       
        
        
        }
        }
    }//GEN-LAST:event_JBCheckoutActionPerformed
    
    private void JBCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCancelActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null, "Terima kasih sudah mampir ke toko kami :D", "Toko Laptop Online", JOptionPane.INFORMATION_MESSAGE);
         this.setVisible(false);
         new Login().setVisible(true);
         
    }//GEN-LAST:event_JBCancelActionPerformed

    private void TxtNominalBayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNominalBayarKeyReleased
        // TODO add your handling code here:
        int bayar = Integer.parseInt(TxtNominalBayar.getText());
        int kembalian = bayar-Total_harga;
        
            TxtKembalian.setText(String.valueOf(kembalian));
    }//GEN-LAST:event_TxtNominalBayarKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        cancel();
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TokoLaptop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TokoLaptop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TokoLaptop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TokoLaptop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TokoLaptop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBEkspedisi;
    private javax.swing.JComboBox<String> CBPilihanLaptop;
    private javax.swing.JButton JBCancel;
    private javax.swing.JButton JBCheckout;
    private javax.swing.JTextField TxtAlamat;
    private javax.swing.JTextField TxtBerat;
    private javax.swing.JTextField TxtHargaBarang;
    private javax.swing.JTextField TxtKembalian;
    private javax.swing.JTextField TxtNamaPelanggan;
    private javax.swing.JTextField TxtNominalBayar;
    private javax.swing.JTextField TxtOngkir;
    private javax.swing.JTextField TxtTotalHarga;
    private javax.swing.JTextField TxtTotalOngkir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
